services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=${DB_HOST:-localhost}
    command: >
      sh -c "if [ \"$NODE_ENV\" = 'production' ]; then npm run build; npm run start:prod; else npm run start:dev; fi; npx sequelize-cli db:seed:all"
  postgres:
    image: postgres:9.6
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - './dbdata:/var/lib/postgresql/data'

networks:
  app-network:
    driver: bridge
