services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - .:/app
    environment:
      - DB_HOST=${DB_HOST:-localhost}
    command: >
      sh -c "if [ \"$NODE_ENV\" = 'production' ]; then npm run build; npm run start:prod; else npm run start:dev; fi;"

    depends_on:
      - postgres
      - db-seed
  postgres:
    image: postgres:9.6
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - './dbdata:/var/lib/postgresql/data'

  db-seed:
    build: .
    command: sh -c "npx sequelize-cli db:seed:all || echo 'Seeding already applied'"
    depends_on:
      - postgres
    environment:
      - DB_HOST=${DB_HOST:-postgres}
    volumes:
      - .:/app
